import { createContext, useContext, useState, useEffect } from 'react';
import { fetchSettings } from '../api/settings';

const translations = {
  en: {
    menu: 'Menu',
    dashboard: 'Dashboard',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    cancel: 'Cancel',
    update: 'Update Item',
    saving: 'Saving…',
    all: 'All',
    heroTitle: 'Our Menu',
    saveLanguages: 'Save Languages',
    menuLanguages: 'Menu Languages',
    menuCategories: 'Menu Categories',
    currentPromotions: 'Current Promotions',
    forEveryone: 'For Everyone',
    for: 'For',
    expired: 'Expired',
    footerTagline: 'Authentic Flavors · Crafted With Love',
    hero: {
      tagline: 'Fine Dining Experience',
      subtitle: 'Authentic flavors from Central Asia, crafted with the finest ingredients',
      scroll: 'Scroll',
    },
    specialOffers: 'Special Offers',
    noItems: 'No items in this category yet.',
    loading: 'Loading menu…',
    restaurantDashboard: 'Restaurant Dashboard',
    itemsInMenu: 'items in the menu',
    globalDiscounts: 'Global Discounts',
    addDiscount: 'Add Discount',
    noDiscounts: 'No discounts yet.',
    discountTitle: 'Title',
    discountPct: 'Discount %',
    appliesTo: 'Applies To',
    everyone: 'Everyone',
    specificGroup: 'Specific Group',
    startTime: 'Start Time',
    endTime: 'End Time',
    active: 'Active',
    edit: 'Edit',
    delete: 'Delete',
    image: 'Image',
    title: 'Title',
    price: 'Price (USD)',
    category: 'Category',
    ingredients: 'Ingredients',
    discountSection: 'Item Discount',
    discountActive: 'Discount Active',
    discountPercent: 'Discount %',
    discountStart: 'Discount Start',
    discountEnd: 'Discount End',
    confirmDelete: 'Confirm Delete',
    doYouWantToDelete: 'Do you really want to delete this',
    yesDelete: 'Yes, Delete',
    noItemsYet: 'No items yet.',
    addFirstItem: 'Add your first item',
    off: 'OFF',
    sale: 'SALE',
    activeNow: 'Active Now',
    until: 'until',
    footerRights: '© 2024 Luxe Kitchen. All rights reserved.',
    langSettingsSubtitle: 'Select which languages your menu items must be filled in',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    saved: 'Saved',
    translateDiscount: 'Translate discount name',
    discountDisplayName: 'Discount Display Name',
    saveCategories: 'Save Categories',
    categorySettingsSubtitle: 'Select which categories to display on your menu',
    drinks: 'Drinks',
    main: 'Main Dishes',
    salads: 'Salads',
    soups: 'Soups',
    desserts: 'Desserts',
    bakery: 'Bakery',
    pastry: 'Pastry',
    appetizers: 'Appetizers',
    dips: 'Dips',
    sauces: 'Sauces',
    bestsellers: 'Bestsellers',
    combo: 'Combo',
    offers: 'Offers',
    additives: 'Additives',
    seafood: 'Seafood',
    pizza: 'Pizza',
    fastfood: 'Fast Food',
    burgers: 'Burgers',
    hotdogs: 'Hot Dogs',
    vegetarian: 'Vegetarian',
    sushi: 'Sushi',
    special: 'Special Dishes',
    targetingLabel: 'Targeting',
    targetingHint: 'leave empty = all items',
    specificItems: 'Specific Items',
    chooseFile: 'Choose file',
    noFileChosen: 'No file chosen',
    orPasteImageUrl: 'or paste an image URL',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: 'List the main ingredients…',
    titlePlaceholder: 'e.g. Grilled Salmon',
    languages: { en: 'English', ru: 'Russian', uz: 'Uzbek', pl: 'Polish', es: 'Spanish', tr: 'Turkish', ar: 'Arabic', zh: 'Chinese', ja: 'Japanese', ko: 'Korean', pt: 'Portuguese', fr: 'French', it: 'Italian' },
    required: 'required',
    optional: 'optional',
    currency: 'Currency',
  },
  ru: {
    menu: 'Меню',
    dashboard: 'Панель',
    addItem: 'Добавить',
    editItem: 'Редактировать',
    cancel: 'Отмена',
    update: 'Обновить',
    saving: 'Сохранение…',
    all: 'Все',
    heroTitle: 'Наше меню',
    saveLanguages: 'Сохранить языки',
    menuLanguages: 'Языки меню',
    menuCategories: 'Категории меню',
    currentPromotions: 'Текущие акции',
    forEveryone: 'Для всех',
    for: 'Для',
    expired: 'Истёк',
    footerTagline: 'Аутентичные вкусы · Приготовленные с любовью',
    hero: {
      tagline: 'Изысканный ужин',
      subtitle: 'Аутентичные вкусы Центральной Азии, приготовленные из лучших ингредиентов',
      scroll: 'Листать',
    },
    specialOffers: 'Специальные предложения',
    noItems: 'Нет позиций в этой категории.',
    loading: 'Загрузка меню…',
    restaurantDashboard: 'Панель управления',
    itemsInMenu: 'позиций в меню',
    globalDiscounts: 'Глобальные скидки',
    addDiscount: 'Добавить скидку',
    noDiscounts: 'Скидок пока нет.',
    discountTitle: 'Название',
    discountPct: 'Скидка %',
    appliesTo: 'Применяется к',
    everyone: 'Всем',
    specificGroup: 'Конкретная группа',
    startTime: 'Начало',
    endTime: 'Конец',
    active: 'Активно',
    edit: 'Редактировать',
    delete: 'Удалить',
    image: 'Изображение',
    title: 'Название',
    price: 'Цена (USD)',
    category: 'Категория',
    ingredients: 'Ингредиенты',
    discountSection: 'Скидка на блюдо',
    discountActive: 'Скидка активна',
    discountPercent: 'Скидка %',
    discountStart: 'Начало скидки',
    discountEnd: 'Конец скидки',
    confirmDelete: 'Подтвердить удаление',
    doYouWantToDelete: 'Вы действительно хотите удалить',
    yesDelete: 'Да, удалить',
    noItemsYet: 'Нет позиций.',
    addFirstItem: 'Добавить первую позицию',
    off: 'СКИДКА',
    sale: 'АКЦИЯ',
    activeNow: 'Активно',
    until: 'до',
    footerRights: '© 2024 Luxe Kitchen. Все права защищены.',
    langSettingsSubtitle: 'Выберите языки для заполнения пунктов меню',
    addCategory: 'Добавить категорию',
    editCategory: 'Редактировать категорию',
    saved: 'Сохранено',
    translateDiscount: 'Перевести название скидки',
    discountDisplayName: 'Отображаемое название',
    saveCategories: 'Сохранить категории',
    categorySettingsSubtitle: 'Выберите категории для отображения в меню',
    drinks: 'Напитки',
    main: 'Основные блюда',
    salads: 'Салаты',
    soups: 'Супы',
    desserts: 'Десерты',
    bakery: 'Выпечка',
    pastry: 'Пастри',
    appetizers: 'Закуски',
    dips: 'Соусы-дипы',
    sauces: 'Соусы',
    bestsellers: 'Хиты продаж',
    combo: 'Комбо',
    offers: 'Акции',
    additives: 'Добавки',
    seafood: 'Морепродукты',
    pizza: 'Пицца',
    fastfood: 'Фастфуд',
    burgers: 'Бургеры',
    hotdogs: 'Хот-доги',
    vegetarian: 'Вегетарианское',
    sushi: 'Суши',
    special: 'Фирменные блюда',
    targetingLabel: 'Таргетинг',
    targetingHint: 'оставьте пустым = все блюда',
    specificItems: 'Конкретные блюда',
    chooseFile: 'Выбрать файл',
    noFileChosen: 'Файл не выбран',
    orPasteImageUrl: 'или вставьте URL изображения',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: 'Перечислите основные ингредиенты…',
    titlePlaceholder: 'например, Жареный лосось',
    languages: { en: 'Английский', ru: 'Русский', uz: 'Узбекский', pl: 'Польский', es: 'Испанский', tr: 'Турецкий', ar: 'Арабский', zh: 'Китайский', ja: 'Японский', ko: 'Корейский', pt: 'Португальский', fr: 'Французский', it: 'Итальянский' },
    required: 'обязательно',
    optional: 'необязательно',
    currency: 'Валюта',
  },
  uz: {
    menu: 'Menyu',
    dashboard: 'Boshqaruv',
    addItem: "Qo'shish",
    editItem: 'Tahrirlash',
    cancel: 'Bekor qilish',
    update: 'Yangilash',
    saving: 'Saqlanmoqda…',
    all: 'Barchasi',
    heroTitle: 'Bizning menyu',
    saveLanguages: 'Tillarni saqlash',
    menuLanguages: 'Menyu tillari',
    menuCategories: 'Menyu kategoriyalari',
    currentPromotions: 'Joriy aksiyalar',
    forEveryone: 'Hammaga',
    for: 'Uchun',
    expired: 'Tugadi',
    footerTagline: 'Haqiqiy ta\'mlar · Muhabbat bilan tayyorlangan',
    hero: {
      tagline: 'Hashamatli oshxona',
      subtitle: "O'rta Osiyo autentik ta'mlari, eng yaxshi ingredientlardan tayyorlangan",
      scroll: 'Aylantirish',
    },
    specialOffers: 'Maxsus takliflar',
    noItems: "Bu kategoriyada mahsulot yo'q.",
    loading: 'Menyu yuklanmoqda…',
    restaurantDashboard: 'Boshqaruv paneli',
    itemsInMenu: 'ta menyu elementi',
    globalDiscounts: 'Global chegirmalar',
    addDiscount: "Chegirma qo'shish",
    noDiscounts: "Hali chegirma yo'q.",
    discountTitle: 'Sarlavha',
    discountPct: 'Chegirma %',
    appliesTo: 'Kimga tegishli',
    everyone: 'Hammaga',
    specificGroup: 'Maxsus guruh',
    startTime: 'Boshlanish',
    endTime: 'Tugash',
    active: 'Faol',
    edit: 'Tahrirlash',
    delete: "O'chirish",
    image: 'Rasm',
    title: 'Sarlavha',
    price: 'Narx (USD)',
    category: 'Kategoriya',
    ingredients: 'Ingredientlar',
    discountSection: 'Mahsulot chegirmasi',
    discountActive: 'Chegirma faol',
    discountPercent: 'Chegirma %',
    discountStart: 'Chegirma boshlanishi',
    discountEnd: 'Chegirma tugashi',
    confirmDelete: "O'chirishni tasdiqlang",
    doYouWantToDelete: "Haqiqatan ham o'chirmoqchimisiz",
    yesDelete: "Ha, o'chirish",
    noItemsYet: "Hali mahsulot yo'q.",
    addFirstItem: "Birinchi mahsulotni qo'shish",
    off: 'CHEGIRMA',
    sale: 'AKSIYA',
    activeNow: 'Faol',
    until: 'gacha',
    footerRights: "© 2024 Luxe Kitchen. Barcha huquqlar himoyalangan.",
    langSettingsSubtitle: "Menyu elementlari qaysi tillarda to'ldirilishini tanlang",
    addCategory: "Kategoriya qo'shish",
    editCategory: 'Kategoriyani tahrirlash',
    saved: 'Saqlandi',
    translateDiscount: "Chegirma nomini tarjima qilish",
    discountDisplayName: "Ko'rsatiladigan nom",
    saveCategories: "Kategoriyalarni saqlash",
    categorySettingsSubtitle: "Menyuda ko'rsatiladigan kategoriyalarni tanlang",
    drinks: 'Ichimliklar',
    main: 'Asosiy taomlar',
    salads: 'Salatlar',
    soups: "Sho'rvalar",
    desserts: 'Shirinliklar',
    bakery: 'Non mahsulotlari',
    pastry: 'Pishiriqlar',
    appetizers: 'Mazalar',
    dips: 'Diplar',
    sauces: 'Souslar',
    bestsellers: "Eng ko'p sotiladigan",
    combo: 'Kombo',
    offers: 'Aksiyalar',
    additives: "Qo'shimchalar",
    seafood: 'Dengiz mahsulotlari',
    pizza: 'Pizza',
    fastfood: 'Tez taomlar',
    burgers: 'Burgerlar',
    hotdogs: 'Hot-doglar',
    vegetarian: 'Vegetarian',
    sushi: 'Sushi',
    special: 'Maxsus taomlar',
    targetingLabel: 'Maqsadli guruh',
    targetingHint: "bo'sh qoldiring = barcha mahsulotlar",
    specificItems: 'Maxsus mahsulotlar',
    chooseFile: 'Fayl tanlash',
    noFileChosen: 'Fayl tanlanmadi',
    orPasteImageUrl: 'yoki rasm URL manzilini joylashtiring',
    imageUrlPlaceholder: 'https://misol.com/rasm.jpg',
    ingredientsPlaceholder: 'Asosiy ingredientlarni kiriting…',
    titlePlaceholder: 'masalan: Panjara losos',
    languages: { en: 'Inglizcha', ru: 'Ruscha', uz: "O'zbekcha", pl: 'Polyakcha', es: 'Ispancha', tr: 'Turkcha', ar: 'Arabcha', zh: 'Xitoycha', ja: 'Yaponcha', ko: 'Koreyscha', pt: 'Portugalcha', fr: 'Fransuzcha', it: 'Italyancha' },
    required: 'majburiy',
    optional: 'ixtiyoriy',
    currency: 'Pul birligi',
  },
  pl: {
    menu: 'Menu',
    dashboard: 'Panel',
    addItem: 'Dodaj',
    editItem: 'Edytuj',
    cancel: 'Anuluj',
    update: 'Zaktualizuj',
    saving: 'Zapisywanie…',
    all: 'Wszystkie',
    heroTitle: 'Nasze menu',
    saveLanguages: 'Zapisz języki',
    menuLanguages: 'Języki menu',
    menuCategories: 'Kategorie menu',
    currentPromotions: 'Bieżące promocje',
    forEveryone: 'Dla wszystkich',
    for: 'Dla',
    expired: 'Wygasło',
    footerTagline: 'Autentyczne smaki · Przygotowane z miłością',
    hero: {
      tagline: 'Wykwintna kuchnia',
      subtitle: 'Autentyczne smaki Azji Środkowej, przygotowane z najlepszych składników',
      scroll: 'Przewiń',
    },
    specialOffers: 'Oferty specjalne',
    noItems: 'Brak pozycji w tej kategorii.',
    loading: 'Ładowanie menu…',
    restaurantDashboard: 'Panel restauracji',
    itemsInMenu: 'pozycji w menu',
    globalDiscounts: 'Globalne zniżki',
    addDiscount: 'Dodaj zniżkę',
    noDiscounts: 'Brak zniżek.',
    discountTitle: 'Tytuł',
    discountPct: 'Zniżka %',
    appliesTo: 'Dotyczy',
    everyone: 'Wszyscy',
    specificGroup: 'Konkretna grupa',
    startTime: 'Początek',
    endTime: 'Koniec',
    active: 'Aktywne',
    edit: 'Edytuj',
    delete: 'Usuń',
    image: 'Obraz',
    title: 'Tytuł',
    price: 'Cena (USD)',
    category: 'Kategoria',
    ingredients: 'Składniki',
    discountSection: 'Zniżka na produkt',
    discountActive: 'Zniżka aktywna',
    discountPercent: 'Zniżka %',
    discountStart: 'Początek zniżki',
    discountEnd: 'Koniec zniżki',
    confirmDelete: 'Potwierdź usunięcie',
    doYouWantToDelete: 'Czy chcesz usunąć',
    yesDelete: 'Tak, usuń',
    noItemsYet: 'Brak pozycji.',
    addFirstItem: 'Dodaj pierwszą pozycję',
    off: 'ZNIŻKA',
    sale: 'PROMOCJA',
    activeNow: 'Aktywne',
    until: 'do',
    footerRights: '© 2024 Luxe Kitchen. Wszelkie prawa zastrzeżone.',
    langSettingsSubtitle: 'Wybierz języki, w których mają być wypełnione pozycje menu',
    addCategory: 'Dodaj kategorię',
    editCategory: 'Edytuj kategorię',
    saved: 'Zapisano',
    translateDiscount: 'Przetłumacz nazwę zniżki',
    discountDisplayName: 'Wyświetlana nazwa',
    saveCategories: 'Zapisz kategorie',
    categorySettingsSubtitle: 'Wybierz kategorie do wyświetlenia w menu',
    drinks: 'Napoje',
    main: 'Dania główne',
    salads: 'Sałatki',
    soups: 'Zupy',
    desserts: 'Desery',
    bakery: 'Pieczywo',
    pastry: 'Ciasta',
    appetizers: 'Przystawki',
    dips: 'Dipy',
    sauces: 'Sosy',
    bestsellers: 'Bestsellery',
    combo: 'Zestawy',
    offers: 'Oferty',
    additives: 'Dodatki',
    seafood: 'Owoce morza',
    pizza: 'Pizza',
    fastfood: 'Fast food',
    burgers: 'Burgery',
    hotdogs: 'Hot dogi',
    vegetarian: 'Wegetariańskie',
    sushi: 'Sushi',
    special: 'Specjalności',
    targetingLabel: 'Targetowanie',
    targetingHint: 'zostaw puste = wszystkie pozycje',
    specificItems: 'Konkretne pozycje',
    chooseFile: 'Wybierz plik',
    noFileChosen: 'Nie wybrano pliku',
    orPasteImageUrl: 'lub wklej URL obrazu',
    imageUrlPlaceholder: 'https://przyklad.com/obraz.jpg',
    ingredientsPlaceholder: 'Wymień główne składniki…',
    titlePlaceholder: 'np. Grillowany łosoś',
    languages: { en: 'Angielski', ru: 'Rosyjski', uz: 'Uzbecki', pl: 'Polski', es: 'Hiszpański', tr: 'Turecki', ar: 'Arabski', zh: 'Chiński', ja: 'Japoński', ko: 'Koreański', pt: 'Portugalski', fr: 'Francuski', it: 'Włoski' },
    required: 'wymagane',
    optional: 'opcjonalne',
    currency: 'Waluta',
  },
  es: {
    menu: 'Menú',
    dashboard: 'Panel',
    addItem: 'Agregar',
    editItem: 'Editar',
    cancel: 'Cancelar',
    update: 'Actualizar',
    saving: 'Guardando…',
    all: 'Todos',
    heroTitle: 'Nuestro menú',
    saveLanguages: 'Guardar idiomas',
    menuLanguages: 'Idiomas del menú',
    menuCategories: 'Categorías del menú',
    currentPromotions: 'Promociones actuales',
    forEveryone: 'Para todos',
    for: 'Para',
    expired: 'Caducado',
    footerTagline: 'Sabores auténticos · Elaborados con amor',
    hero: {
      tagline: 'Gastronomía fina',
      subtitle: 'Sabores auténticos de Asia Central, elaborados con los mejores ingredientes',
      scroll: 'Desplazar',
    },
    specialOffers: 'Ofertas especiales',
    noItems: 'Sin elementos en esta categoría.',
    loading: 'Cargando menú…',
    restaurantDashboard: 'Panel del restaurante',
    itemsInMenu: 'elementos en el menú',
    globalDiscounts: 'Descuentos globales',
    addDiscount: 'Agregar descuento',
    noDiscounts: 'Sin descuentos.',
    discountTitle: 'Título',
    discountPct: 'Descuento %',
    appliesTo: 'Aplica a',
    everyone: 'Todos',
    specificGroup: 'Grupo específico',
    startTime: 'Inicio',
    endTime: 'Fin',
    active: 'Activo',
    edit: 'Editar',
    delete: 'Eliminar',
    image: 'Imagen',
    title: 'Título',
    price: 'Precio (USD)',
    category: 'Categoría',
    ingredients: 'Ingredientes',
    discountSection: 'Descuento del artículo',
    discountActive: 'Descuento activo',
    discountPercent: 'Descuento %',
    discountStart: 'Inicio del descuento',
    discountEnd: 'Fin del descuento',
    confirmDelete: 'Confirmar eliminación',
    doYouWantToDelete: '¿Desea eliminar',
    yesDelete: 'Sí, eliminar',
    noItemsYet: 'Sin elementos aún.',
    addFirstItem: 'Agregar primer elemento',
    off: 'DESC',
    sale: 'OFERTA',
    activeNow: 'Activo',
    until: 'hasta',
    footerRights: '© 2024 Luxe Kitchen. Todos los derechos reservados.',
    langSettingsSubtitle: 'Selecciona los idiomas en los que deben completarse los elementos del menú',
    addCategory: 'Agregar categoría',
    editCategory: 'Editar categoría',
    saved: 'Guardado',
    translateDiscount: 'Traducir nombre del descuento',
    discountDisplayName: 'Nombre para mostrar',
    saveCategories: 'Guardar categorías',
    categorySettingsSubtitle: 'Selecciona las categorías a mostrar en el menú',
    drinks: 'Bebidas',
    main: 'Platos principales',
    salads: 'Ensaladas',
    soups: 'Sopas',
    desserts: 'Postres',
    bakery: 'Panadería',
    pastry: 'Pastelería',
    appetizers: 'Entrantes',
    dips: 'Salsas para mojar',
    sauces: 'Salsas',
    bestsellers: 'Los más vendidos',
    combo: 'Combos',
    offers: 'Ofertas',
    additives: 'Aditivos',
    seafood: 'Mariscos',
    pizza: 'Pizza',
    fastfood: 'Comida rápida',
    burgers: 'Hamburguesas',
    hotdogs: 'Perritos calientes',
    vegetarian: 'Vegetariano',
    sushi: 'Sushi',
    special: 'Platos especiales',
    targetingLabel: 'Orientación',
    targetingHint: 'dejar vacío = todos los artículos',
    specificItems: 'Artículos específicos',
    chooseFile: 'Elegir archivo',
    noFileChosen: 'No se ha elegido archivo',
    orPasteImageUrl: 'o pega una URL de imagen',
    imageUrlPlaceholder: 'https://ejemplo.com/imagen.jpg',
    ingredientsPlaceholder: 'Lista los ingredientes principales…',
    titlePlaceholder: 'ej. Salmón a la parrilla',
    languages: { en: 'Inglés', ru: 'Ruso', uz: 'Uzbeko', pl: 'Polaco', es: 'Español', tr: 'Turco', ar: 'Árabe', zh: 'Chino', ja: 'Japonés', ko: 'Coreano', pt: 'Portugués', fr: 'Francés', it: 'Italiano' },
    required: 'obligatorio',
    optional: 'opcional',
    currency: 'Moneda',
  },
  tr: {
    menu: 'Menü',
    dashboard: 'Panel',
    addItem: 'Ekle',
    editItem: 'Düzenle',
    cancel: 'İptal',
    update: 'Güncelle',
    saving: 'Kaydediliyor…',
    all: 'Tümü',
    heroTitle: 'Menümüz',
    saveLanguages: 'Dilleri Kaydet',
    menuLanguages: 'Menü Dilleri',
    menuCategories: 'Menü Kategorileri',
    currentPromotions: 'Güncel Kampanyalar',
    forEveryone: 'Herkes İçin',
    for: 'İçin',
    expired: 'Süresi Doldu',
    footerTagline: 'Özgün Lezzetler · Sevgiyle Hazırlanmış',
    hero: {
      tagline: 'İnce Yemek Deneyimi',
      subtitle: "Orta Asya'nın özgün lezzetleri, en iyi malzemelerle hazırlanmış",
      scroll: 'Kaydır',
    },
    specialOffers: 'Özel Teklifler',
    noItems: 'Bu kategoride ürün yok.',
    loading: 'Menü yükleniyor…',
    restaurantDashboard: 'Restoran Paneli',
    itemsInMenu: 'menüdeki ürün',
    globalDiscounts: 'Global İndirimler',
    addDiscount: 'İndirim Ekle',
    noDiscounts: 'Henüz indirim yok.',
    discountTitle: 'Başlık',
    discountPct: 'İndirim %',
    appliesTo: 'Uygulanır',
    everyone: 'Herkes',
    specificGroup: 'Belirli Grup',
    startTime: 'Başlangıç',
    endTime: 'Bitiş',
    active: 'Aktif',
    edit: 'Düzenle',
    delete: 'Sil',
    image: 'Resim',
    title: 'Başlık',
    price: 'Fiyat (USD)',
    category: 'Kategori',
    ingredients: 'Malzemeler',
    discountSection: 'Ürün İndirimi',
    discountActive: 'İndirim Aktif',
    discountPercent: 'İndirim %',
    discountStart: 'İndirim Başlangıcı',
    discountEnd: 'İndirim Bitişi',
    confirmDelete: 'Silmeyi Onayla',
    doYouWantToDelete: 'Silmek istiyor musunuz',
    yesDelete: 'Evet, Sil',
    noItemsYet: 'Henüz ürün yok.',
    addFirstItem: 'İlk ürünü ekle',
    off: 'İNDİRİM',
    sale: 'KAMPANYA',
    activeNow: 'Aktif',
    until: 'kadar',
    footerRights: '© 2024 Luxe Kitchen. Tüm hakları saklıdır.',
    langSettingsSubtitle: 'Menü öğelerinin hangi dillerde doldurulacağını seçin',
    addCategory: 'Kategori Ekle',
    editCategory: 'Kategoriyi Düzenle',
    saved: 'Kaydedildi',
    translateDiscount: 'İndirim adını çevir',
    discountDisplayName: 'Görünen Ad',
    saveCategories: 'Kategorileri Kaydet',
    categorySettingsSubtitle: 'Menüde gösterilecek kategorileri seçin',
    drinks: 'İçecekler',
    main: 'Ana Yemekler',
    salads: 'Salatalar',
    soups: 'Çorbalar',
    desserts: 'Tatlılar',
    bakery: 'Fırın Ürünleri',
    pastry: 'Börekler',
    appetizers: 'Mezeler',
    dips: 'Diplar',
    sauces: 'Soslar',
    bestsellers: 'En Çok Satanlar',
    combo: 'Kombolar',
    offers: 'Teklifler',
    additives: 'Ekstralar',
    seafood: 'Deniz Ürünleri',
    pizza: 'Pizza',
    fastfood: 'Fast Food',
    burgers: 'Burgerlar',
    hotdogs: 'Sosisli Sandviçler',
    vegetarian: 'Vejeteryan',
    sushi: 'Sushi',
    special: 'Özel Yemekler',
    targetingLabel: 'Hedefleme',
    targetingHint: 'boş bırakın = tüm ürünler',
    specificItems: 'Belirli Ürünler',
    chooseFile: 'Dosya seç',
    noFileChosen: 'Dosya seçilmedi',
    orPasteImageUrl: "veya resim URL'sini yapıştırın",
    imageUrlPlaceholder: 'https://ornek.com/resim.jpg',
    ingredientsPlaceholder: 'Ana malzemeleri listeleyin…',
    titlePlaceholder: 'örn. Izgara Somon',
    languages: { en: 'İngilizce', ru: 'Rusça', uz: 'Özbekçe', pl: 'Lehçe', es: 'İspanyolca', tr: 'Türkçe', ar: 'Arapça', zh: 'Çince', ja: 'Japonca', ko: 'Korece', pt: 'Portekizce', fr: 'Fransızca', it: 'İtalyanca' },
    required: 'gerekli',
    optional: 'isteğe bağlı',
    currency: 'Para birimi',
  },
  ar: {
    menu: 'قائمة الطعام',
    dashboard: 'لوحة التحكم',
    addItem: 'إضافة',
    editItem: 'تعديل',
    cancel: 'إلغاء',
    update: 'تحديث',
    saving: 'جارٍ الحفظ…',
    all: 'الكل',
    heroTitle: 'قائمتنا',
    saveLanguages: 'حفظ اللغات',
    menuLanguages: 'لغات القائمة',
    menuCategories: 'فئات القائمة',
    currentPromotions: 'العروض الحالية',
    forEveryone: 'للجميع',
    for: 'لـ',
    expired: 'انتهت المدة',
    footerTagline: 'نكهات أصيلة · مُعدَّة بمحبة',
    hero: {
      tagline: 'تجربة طعام راقية',
      subtitle: 'نكهات أصيلة من آسيا الوسطى، مُعدَّة بأجود المكونات',
      scroll: 'تمرير',
    },
    specialOffers: 'عروض خاصة',
    noItems: 'لا توجد عناصر في هذه الفئة.',
    loading: 'جارٍ تحميل القائمة…',
    restaurantDashboard: 'لوحة تحكم المطعم',
    itemsInMenu: 'عناصر في القائمة',
    globalDiscounts: 'الخصومات العامة',
    addDiscount: 'إضافة خصم',
    noDiscounts: 'لا توجد خصومات.',
    discountTitle: 'العنوان',
    discountPct: 'نسبة الخصم',
    appliesTo: 'ينطبق على',
    everyone: 'الجميع',
    specificGroup: 'مجموعة محددة',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    active: 'نشط',
    edit: 'تعديل',
    delete: 'حذف',
    image: 'صورة',
    title: 'العنوان',
    price: 'السعر (USD)',
    category: 'الفئة',
    ingredients: 'المكونات',
    discountSection: 'خصم العنصر',
    discountActive: 'الخصم نشط',
    discountPercent: 'نسبة الخصم',
    discountStart: 'بداية الخصم',
    discountEnd: 'نهاية الخصم',
    confirmDelete: 'تأكيد الحذف',
    doYouWantToDelete: 'هل تريد حذف',
    yesDelete: 'نعم، حذف',
    noItemsYet: 'لا توجد عناصر.',
    addFirstItem: 'أضف العنصر الأول',
    off: 'خصم',
    sale: 'تخفيض',
    activeNow: 'نشط',
    until: 'حتى',
    footerRights: '© 2024 Luxe Kitchen. جميع الحقوق محفوظة.',
    langSettingsSubtitle: 'اختر اللغات التي يجب ملء عناصر القائمة بها',
    addCategory: 'إضافة فئة',
    editCategory: 'تعديل الفئة',
    saved: 'تم الحفظ',
    translateDiscount: 'ترجمة اسم الخصم',
    discountDisplayName: 'اسم العرض',
    saveCategories: 'حفظ الفئات',
    categorySettingsSubtitle: 'اختر الفئات التي تريد عرضها في القائمة',
    drinks: 'مشروبات',
    main: 'أطباق رئيسية',
    salads: 'سلطات',
    soups: 'شوربات',
    desserts: 'حلويات',
    bakery: 'مخبوزات',
    pastry: 'معجنات',
    appetizers: 'مقبلات',
    dips: 'صلصات غمس',
    sauces: 'صلصات',
    bestsellers: 'الأكثر مبيعًا',
    combo: 'وجبات كومبو',
    offers: 'عروض',
    additives: 'إضافات',
    seafood: 'مأكولات بحرية',
    pizza: 'بيتزا',
    fastfood: 'وجبات سريعة',
    burgers: 'برغر',
    hotdogs: 'هوت دوغ',
    vegetarian: 'نباتي',
    sushi: 'سوشي',
    special: 'أطباق خاصة',
    targetingLabel: 'الاستهداف',
    targetingHint: 'اتركه فارغًا = جميع العناصر',
    specificItems: 'عناصر محددة',
    chooseFile: 'اختر ملفًا',
    noFileChosen: 'لم يتم اختيار ملف',
    orPasteImageUrl: 'أو الصق رابط الصورة',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: 'أدرج المكونات الرئيسية…',
    titlePlaceholder: 'مثال: سلمون مشوي',
    languages: { en: 'الإنجليزية', ru: 'الروسية', uz: 'الأوزبكية', pl: 'البولندية', es: 'الإسبانية', tr: 'التركية', ar: 'العربية', zh: 'الصينية', ja: 'اليابانية', ko: 'الكورية', pt: 'البرتغالية', fr: 'الفرنسية', it: 'الإيطالية' },
    required: 'مطلوب',
    optional: 'اختياري',
    currency: 'العملة',
  },
  zh: {
    menu: '菜单',
    dashboard: '控制台',
    addItem: '添加',
    editItem: '编辑',
    cancel: '取消',
    update: '更新',
    saving: '保存中…',
    all: '全部',
    heroTitle: '我们的菜单',
    saveLanguages: '保存语言',
    menuLanguages: '菜单语言',
    menuCategories: '菜单分类',
    currentPromotions: '当前促销',
    forEveryone: '适合所有人',
    for: '为',
    expired: '已过期',
    footerTagline: '正宗风味 · 用心制作',
    hero: {
      tagline: '精致餐饮体验',
      subtitle: '来自中亚的正宗风味，以最优质的食材精心制作',
      scroll: '滚动',
    },
    specialOffers: '特别优惠',
    noItems: '此类别暂无菜品。',
    loading: '菜单加载中…',
    restaurantDashboard: '餐厅控制台',
    itemsInMenu: '个菜单项',
    globalDiscounts: '全局折扣',
    addDiscount: '添加折扣',
    noDiscounts: '暂无折扣。',
    discountTitle: '标题',
    discountPct: '折扣 %',
    appliesTo: '适用于',
    everyone: '所有人',
    specificGroup: '特定群体',
    startTime: '开始时间',
    endTime: '结束时间',
    active: '活跃',
    edit: '编辑',
    delete: '删除',
    image: '图片',
    title: '标题',
    price: '价格 (USD)',
    category: '类别',
    ingredients: '食材',
    discountSection: '菜品折扣',
    discountActive: '折扣有效',
    discountPercent: '折扣 %',
    discountStart: '折扣开始',
    discountEnd: '折扣结束',
    confirmDelete: '确认删除',
    doYouWantToDelete: '确定要删除',
    yesDelete: '是的，删除',
    noItemsYet: '暂无菜品。',
    addFirstItem: '添加第一个菜品',
    off: '折扣',
    sale: '特卖',
    activeNow: '活跃',
    until: '至',
    footerRights: '© 2024 Luxe Kitchen. 保留所有权利。',
    langSettingsSubtitle: '选择菜单项必须填写的语言',
    addCategory: '添加分类',
    editCategory: '编辑分类',
    saved: '已保存',
    translateDiscount: '翻译折扣名称',
    discountDisplayName: '显示名称',
    saveCategories: '保存分类',
    categorySettingsSubtitle: '选择要在菜单上显示的分类',
    drinks: '饮料',
    main: '主菜',
    salads: '沙拉',
    soups: '汤品',
    desserts: '甜点',
    bakery: '烘焙',
    pastry: '糕点',
    appetizers: '开胃菜',
    dips: '蘸酱',
    sauces: '酱料',
    bestsellers: '畅销榜',
    combo: '套餐',
    offers: '优惠',
    additives: '附加品',
    seafood: '海鲜',
    pizza: '比萨',
    fastfood: '快餐',
    burgers: '汉堡',
    hotdogs: '热狗',
    vegetarian: '素食',
    sushi: '寿司',
    special: '特色菜',
    targetingLabel: '定向',
    targetingHint: '留空 = 所有商品',
    specificItems: '特定商品',
    chooseFile: '选择文件',
    noFileChosen: '未选择文件',
    orPasteImageUrl: '或粘贴图片链接',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: '列出主要食材…',
    titlePlaceholder: '例如：烤三文鱼',
    languages: { en: '英语', ru: '俄语', uz: '乌兹别克语', pl: '波兰语', es: '西班牙语', tr: '土耳其语', ar: '阿拉伯语', zh: '中文', ja: '日语', ko: '韩语', pt: '葡萄牙语', fr: '法语', it: '意大利语' },
    required: '必填',
    optional: '可选',
    currency: '货币',
  },
  ja: {
    menu: 'メニュー',
    dashboard: 'ダッシュボード',
    addItem: '追加',
    editItem: '編集',
    cancel: 'キャンセル',
    update: '更新',
    saving: '保存中…',
    all: 'すべて',
    heroTitle: '私たちのメニュー',
    saveLanguages: '言語を保存',
    menuLanguages: 'メニュー言語',
    menuCategories: 'メニューカテゴリ',
    currentPromotions: '現在のプロモーション',
    forEveryone: '全員向け',
    for: '向け',
    expired: '期限切れ',
    footerTagline: '本場の味 · 心を込めて',
    hero: {
      tagline: '高級ダイニング体験',
      subtitle: '中央アジアの本場の味わい、最高の食材で仕上げた一品',
      scroll: 'スクロール',
    },
    specialOffers: '特別オファー',
    noItems: 'このカテゴリにはまだ商品がありません。',
    loading: 'メニューを読み込み中…',
    restaurantDashboard: 'レストランダッシュボード',
    itemsInMenu: '個のメニュー項目',
    globalDiscounts: 'グローバル割引',
    addDiscount: '割引を追加',
    noDiscounts: '割引はまだありません。',
    discountTitle: 'タイトル',
    discountPct: '割引 %',
    appliesTo: '適用対象',
    everyone: '全員',
    specificGroup: '特定グループ',
    startTime: '開始時間',
    endTime: '終了時間',
    active: 'アクティブ',
    edit: '編集',
    delete: '削除',
    image: '画像',
    title: 'タイトル',
    price: '価格 (USD)',
    category: 'カテゴリ',
    ingredients: '食材',
    discountSection: '商品割引',
    discountActive: '割引有効',
    discountPercent: '割引 %',
    discountStart: '割引開始',
    discountEnd: '割引終了',
    confirmDelete: '削除の確認',
    doYouWantToDelete: '削除してもよろしいですか',
    yesDelete: 'はい、削除',
    noItemsYet: 'まだ商品がありません。',
    addFirstItem: '最初の商品を追加',
    off: '割引',
    sale: 'セール',
    activeNow: 'アクティブ',
    until: 'まで',
    footerRights: '© 2024 Luxe Kitchen. 全著作権所有。',
    langSettingsSubtitle: 'メニュー項目を入力する必要がある言語を選択してください',
    addCategory: 'カテゴリを追加',
    editCategory: 'カテゴリを編集',
    saved: '保存済み',
    translateDiscount: '割引名を翻訳する',
    discountDisplayName: '表示名',
    saveCategories: 'カテゴリを保存',
    categorySettingsSubtitle: 'メニューに表示するカテゴリを選択してください',
    drinks: 'ドリンク',
    main: 'メインディッシュ',
    salads: 'サラダ',
    soups: 'スープ',
    desserts: 'デザート',
    bakery: 'ベーカリー',
    pastry: 'ペストリー',
    appetizers: '前菜',
    dips: 'ディップ',
    sauces: 'ソース',
    bestsellers: '人気商品',
    combo: 'セット',
    offers: 'オファー',
    additives: '追加品',
    seafood: 'シーフード',
    pizza: 'ピザ',
    fastfood: 'ファストフード',
    burgers: 'バーガー',
    hotdogs: 'ホットドッグ',
    vegetarian: 'ベジタリアン',
    sushi: '寿司',
    special: '特別料理',
    targetingLabel: 'ターゲット設定',
    targetingHint: '空白 = すべての商品',
    specificItems: '特定の商品',
    chooseFile: 'ファイルを選択',
    noFileChosen: 'ファイルが選択されていません',
    orPasteImageUrl: 'または画像URLを貼り付けてください',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: '主な食材を入力…',
    titlePlaceholder: '例：グリルサーモン',
    languages: { en: '英語', ru: 'ロシア語', uz: 'ウズベク語', pl: 'ポーランド語', es: 'スペイン語', tr: 'トルコ語', ar: 'アラビア語', zh: '中国語', ja: '日本語', ko: '韓国語', pt: 'ポルトガル語', fr: 'フランス語', it: 'イタリア語' },
    required: '必須',
    optional: '任意',
    currency: '通貨',
  },
  ko: {
    menu: '메뉴',
    dashboard: '대시보드',
    addItem: '추가',
    editItem: '편집',
    cancel: '취소',
    update: '업데이트',
    saving: '저장 중…',
    all: '전체',
    heroTitle: '우리 메뉴',
    saveLanguages: '언어 저장',
    menuLanguages: '메뉴 언어',
    menuCategories: '메뉴 카테고리',
    currentPromotions: '현재 프로모션',
    forEveryone: '모든 사람을 위해',
    for: '위해',
    expired: '만료됨',
    footerTagline: '정통 풍미 · 사랑으로 만든',
    hero: {
      tagline: '파인 다이닝 경험',
      subtitle: '중앙아시아의 정통 맛, 최고의 재료로 만든 요리',
      scroll: '스크롤',
    },
    specialOffers: '특별 제공',
    noItems: '이 카테고리에 항목이 없습니다.',
    loading: '메뉴 로딩 중…',
    restaurantDashboard: '레스토랑 대시보드',
    itemsInMenu: '개의 메뉴 항목',
    globalDiscounts: '글로벌 할인',
    addDiscount: '할인 추가',
    noDiscounts: '할인이 없습니다.',
    discountTitle: '제목',
    discountPct: '할인 %',
    appliesTo: '적용 대상',
    everyone: '모든 사람',
    specificGroup: '특정 그룹',
    startTime: '시작 시간',
    endTime: '종료 시간',
    active: '활성',
    edit: '편집',
    delete: '삭제',
    image: '이미지',
    title: '제목',
    price: '가격 (USD)',
    category: '카테고리',
    ingredients: '재료',
    discountSection: '상품 할인',
    discountActive: '할인 활성',
    discountPercent: '할인 %',
    discountStart: '할인 시작',
    discountEnd: '할인 종료',
    confirmDelete: '삭제 확인',
    doYouWantToDelete: '삭제하시겠습니까',
    yesDelete: '예, 삭제',
    noItemsYet: '아직 항목이 없습니다.',
    addFirstItem: '첫 번째 항목 추가',
    off: '할인',
    sale: '세일',
    activeNow: '활성',
    until: '까지',
    footerRights: '© 2024 Luxe Kitchen. 모든 권리 보유.',
    langSettingsSubtitle: '메뉴 항목을 작성해야 하는 언어를 선택하세요',
    addCategory: '카테고리 추가',
    editCategory: '카테고리 편집',
    saved: '저장됨',
    translateDiscount: '할인 이름 번역',
    discountDisplayName: '표시 이름',
    saveCategories: '카테고리 저장',
    categorySettingsSubtitle: '메뉴에 표시할 카테고리를 선택하세요',
    drinks: '음료',
    main: '메인 요리',
    salads: '샐러드',
    soups: '수프',
    desserts: '디저트',
    bakery: '베이커리',
    pastry: '페이스트리',
    appetizers: '애피타이저',
    dips: '딥 소스',
    sauces: '소스',
    bestsellers: '베스트셀러',
    combo: '콤보',
    offers: '할인 메뉴',
    additives: '토핑',
    seafood: '해산물',
    pizza: '피자',
    fastfood: '패스트푸드',
    burgers: '버거',
    hotdogs: '핫도그',
    vegetarian: '채식',
    sushi: '스시',
    special: '특선 요리',
    targetingLabel: '타겟팅',
    targetingHint: '비워두면 = 전체 항목',
    specificItems: '특정 항목',
    chooseFile: '파일 선택',
    noFileChosen: '선택된 파일 없음',
    orPasteImageUrl: '또는 이미지 URL 붙여넣기',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    ingredientsPlaceholder: '주요 재료를 입력하세요…',
    titlePlaceholder: '예: 구운 연어',
    languages: { en: '영어', ru: '러시아어', uz: '우즈베크어', pl: '폴란드어', es: '스페인어', tr: '터키어', ar: '아랍어', zh: '중국어', ja: '일본어', ko: '한국어', pt: '포르투갈어', fr: '프랑스어', it: '이탈리아어' },
    required: '필수',
    optional: '선택',
    currency: '통화',
  },
  pt: {
    menu: 'Menu',
    dashboard: 'Painel',
    addItem: 'Adicionar',
    editItem: 'Editar',
    cancel: 'Cancelar',
    update: 'Atualizar',
    saving: 'A guardar…',
    all: 'Todos',
    heroTitle: 'Nosso cardápio',
    saveLanguages: 'Guardar idiomas',
    menuLanguages: 'Idiomas do menu',
    menuCategories: 'Categorias do menu',
    currentPromotions: 'Promoções actuais',
    forEveryone: 'Para todos',
    for: 'Para',
    expired: 'Expirado',
    footerTagline: 'Sabores autênticos · Feitos com amor',
    hero: {
      tagline: 'Experiência gastronómica',
      subtitle: 'Sabores autênticos da Ásia Central, preparados com os melhores ingredientes',
      scroll: 'Rolar',
    },
    specialOffers: 'Ofertas especiais',
    noItems: 'Sem itens nesta categoria.',
    loading: 'A carregar menu…',
    restaurantDashboard: 'Painel do restaurante',
    itemsInMenu: 'itens no menu',
    globalDiscounts: 'Descontos globais',
    addDiscount: 'Adicionar desconto',
    noDiscounts: 'Sem descontos.',
    discountTitle: 'Título',
    discountPct: 'Desconto %',
    appliesTo: 'Aplica-se a',
    everyone: 'Todos',
    specificGroup: 'Grupo específico',
    startTime: 'Início',
    endTime: 'Fim',
    active: 'Ativo',
    edit: 'Editar',
    delete: 'Eliminar',
    image: 'Imagem',
    title: 'Título',
    price: 'Preço (USD)',
    category: 'Categoria',
    ingredients: 'Ingredientes',
    discountSection: 'Desconto do item',
    discountActive: 'Desconto ativo',
    discountPercent: 'Desconto %',
    discountStart: 'Início do desconto',
    discountEnd: 'Fim do desconto',
    confirmDelete: 'Confirmar eliminação',
    doYouWantToDelete: 'Deseja eliminar',
    yesDelete: 'Sim, eliminar',
    noItemsYet: 'Sem itens ainda.',
    addFirstItem: 'Adicionar primeiro item',
    off: 'DESC',
    sale: 'PROMOÇÃO',
    activeNow: 'Ativo',
    until: 'até',
    footerRights: '© 2024 Luxe Kitchen. Todos os direitos reservados.',
    langSettingsSubtitle: 'Selecione os idiomas em que os itens do menu devem ser preenchidos',
    addCategory: 'Adicionar categoria',
    editCategory: 'Editar categoria',
    saved: 'Guardado',
    translateDiscount: 'Traduzir nome do desconto',
    discountDisplayName: 'Nome de exibição',
    saveCategories: 'Guardar categorias',
    categorySettingsSubtitle: 'Selecione as categorias a exibir no menu',
    drinks: 'Bebidas',
    main: 'Pratos principais',
    salads: 'Saladas',
    soups: 'Sopas',
    desserts: 'Sobremesas',
    bakery: 'Padaria',
    pastry: 'Pastelaria',
    appetizers: 'Entradas',
    dips: 'Molhos para mergulhar',
    sauces: 'Molhos',
    bestsellers: 'Mais vendidos',
    combo: 'Combos',
    offers: 'Ofertas',
    additives: 'Adicionais',
    seafood: 'Frutos do mar',
    pizza: 'Pizza',
    fastfood: 'Fast food',
    burgers: 'Hambúrgueres',
    hotdogs: 'Cachorros-quentes',
    vegetarian: 'Vegetariano',
    sushi: 'Sushi',
    special: 'Pratos especiais',
    targetingLabel: 'Segmentação',
    targetingHint: 'deixar vazio = todos os itens',
    specificItems: 'Itens específicos',
    chooseFile: 'Escolher ficheiro',
    noFileChosen: 'Nenhum ficheiro escolhido',
    orPasteImageUrl: 'ou cole um URL de imagem',
    imageUrlPlaceholder: 'https://exemplo.com/imagem.jpg',
    ingredientsPlaceholder: 'Liste os ingredientes principais…',
    titlePlaceholder: 'ex. Salmão grelhado',
    languages: { en: 'Inglês', ru: 'Russo', uz: 'Uzbeque', pl: 'Polaco', es: 'Espanhol', tr: 'Turco', ar: 'Árabe', zh: 'Chinês', ja: 'Japonês', ko: 'Coreano', pt: 'Português', fr: 'Francês', it: 'Italiano' },
    required: 'obrigatório',
    optional: 'opcional',
    currency: 'Moeda',
  },
  fr: {
    menu: 'Menu',
    dashboard: 'Tableau de bord',
    addItem: 'Ajouter',
    editItem: 'Modifier',
    cancel: 'Annuler',
    update: 'Mettre à jour',
    saving: 'Enregistrement…',
    all: 'Tous',
    heroTitle: 'Notre menu',
    saveLanguages: 'Enregistrer les langues',
    menuLanguages: 'Langues du menu',
    menuCategories: 'Catégories du menu',
    currentPromotions: 'Promotions en cours',
    forEveryone: 'Pour tous',
    for: 'Pour',
    expired: 'Expiré',
    footerTagline: 'Saveurs authentiques · Préparées avec amour',
    hero: {
      tagline: 'Expérience gastronomique',
      subtitle: "Saveurs authentiques d'Asie centrale, élaborées avec les meilleurs ingrédients",
      scroll: 'Défiler',
    },
    specialOffers: 'Offres spéciales',
    noItems: 'Aucun article dans cette catégorie.',
    loading: 'Chargement du menu…',
    restaurantDashboard: 'Tableau de bord',
    itemsInMenu: 'articles au menu',
    globalDiscounts: 'Réductions globales',
    addDiscount: 'Ajouter une réduction',
    noDiscounts: 'Aucune réduction.',
    discountTitle: 'Titre',
    discountPct: 'Réduction %',
    appliesTo: "S'applique à",
    everyone: 'Tout le monde',
    specificGroup: 'Groupe spécifique',
    startTime: 'Début',
    endTime: 'Fin',
    active: 'Actif',
    edit: 'Modifier',
    delete: 'Supprimer',
    image: 'Image',
    title: 'Titre',
    price: 'Prix (USD)',
    category: 'Catégorie',
    ingredients: 'Ingrédients',
    discountSection: "Réduction de l'article",
    discountActive: 'Réduction active',
    discountPercent: 'Réduction %',
    discountStart: 'Début de la réduction',
    discountEnd: 'Fin de la réduction',
    confirmDelete: 'Confirmer la suppression',
    doYouWantToDelete: 'Voulez-vous supprimer',
    yesDelete: 'Oui, supprimer',
    noItemsYet: 'Aucun article.',
    addFirstItem: 'Ajouter le premier article',
    off: 'SOLDE',
    sale: 'PROMO',
    activeNow: 'Actif',
    until: "jusqu'à",
    footerRights: '© 2024 Luxe Kitchen. Tous droits réservés.',
    langSettingsSubtitle: 'Sélectionnez les langues dans lesquelles les éléments du menu doivent être remplis',
    addCategory: 'Ajouter une catégorie',
    editCategory: 'Modifier la catégorie',
    saved: 'Enregistré',
    translateDiscount: 'Traduire le nom de la réduction',
    discountDisplayName: "Nom d'affichage",
    saveCategories: 'Enregistrer les catégories',
    categorySettingsSubtitle: 'Sélectionnez les catégories à afficher dans le menu',
    drinks: 'Boissons',
    main: 'Plats principaux',
    salads: 'Salades',
    soups: 'Soupes',
    desserts: 'Desserts',
    bakery: 'Boulangerie',
    pastry: 'Pâtisserie',
    appetizers: 'Entrées',
    dips: 'Trempettes',
    sauces: 'Sauces',
    bestsellers: 'Meilleures ventes',
    combo: 'Combos',
    offers: 'Offres',
    additives: 'Suppléments',
    seafood: 'Fruits de mer',
    pizza: 'Pizza',
    fastfood: 'Fast food',
    burgers: 'Burgers',
    hotdogs: 'Hot-dogs',
    vegetarian: 'Végétarien',
    sushi: 'Sushi',
    special: 'Plats spéciaux',
    targetingLabel: 'Ciblage',
    targetingHint: 'laisser vide = tous les articles',
    specificItems: 'Articles spécifiques',
    chooseFile: 'Choisir un fichier',
    noFileChosen: 'Aucun fichier choisi',
    orPasteImageUrl: "ou collez une URL d'image",
    imageUrlPlaceholder: 'https://exemple.com/image.jpg',
    ingredientsPlaceholder: 'Listez les ingrédients principaux…',
    titlePlaceholder: 'ex. Saumon grillé',
    languages: { en: 'Anglais', ru: 'Russe', uz: 'Ouzbek', pl: 'Polonais', es: 'Espagnol', tr: 'Turc', ar: 'Arabe', zh: 'Chinois', ja: 'Japonais', ko: 'Coréen', pt: 'Portugais', fr: 'Français', it: 'Italien' },
    required: 'obligatoire',
    optional: 'facultatif',
    currency: 'Devise',
  },
  it: {
    menu: 'Menu',
    dashboard: 'Dashboard',
    addItem: 'Aggiungi',
    editItem: 'Modifica',
    cancel: 'Annulla',
    update: 'Aggiorna',
    saving: 'Salvataggio…',
    all: 'Tutti',
    heroTitle: 'Il nostro menu',
    saveLanguages: 'Salva lingue',
    menuLanguages: 'Lingue del menu',
    menuCategories: 'Categorie del menu',
    currentPromotions: 'Promozioni correnti',
    forEveryone: 'Per tutti',
    for: 'Per',
    expired: 'Scaduto',
    footerTagline: 'Sapori autentici · Preparati con amore',
    hero: {
      tagline: 'Esperienza gastronomica',
      subtitle: "Sapori autentici dall'Asia Centrale, preparati con i migliori ingredienti",
      scroll: 'Scorri',
    },
    specialOffers: 'Offerte speciali',
    noItems: 'Nessun articolo in questa categoria.',
    loading: 'Caricamento menu…',
    restaurantDashboard: 'Dashboard ristorante',
    itemsInMenu: 'articoli nel menu',
    globalDiscounts: 'Sconti globali',
    addDiscount: 'Aggiungi sconto',
    noDiscounts: 'Nessuno sconto.',
    discountTitle: 'Titolo',
    discountPct: 'Sconto %',
    appliesTo: 'Si applica a',
    everyone: 'Tutti',
    specificGroup: 'Gruppo specifico',
    startTime: 'Inizio',
    endTime: 'Fine',
    active: 'Attivo',
    edit: 'Modifica',
    delete: 'Elimina',
    image: 'Immagine',
    title: 'Titolo',
    price: 'Prezzo (USD)',
    category: 'Categoria',
    ingredients: 'Ingredienti',
    discountSection: 'Sconto articolo',
    discountActive: 'Sconto attivo',
    discountPercent: 'Sconto %',
    discountStart: 'Inizio sconto',
    discountEnd: 'Fine sconto',
    confirmDelete: 'Conferma eliminazione',
    doYouWantToDelete: 'Vuoi eliminare',
    yesDelete: 'Sì, elimina',
    noItemsYet: 'Nessun articolo.',
    addFirstItem: 'Aggiungi il primo articolo',
    off: 'SCONTO',
    sale: 'SALDO',
    activeNow: 'Attivo',
    until: 'fino a',
    footerRights: '© 2024 Luxe Kitchen. Tutti i diritti riservati.',
    langSettingsSubtitle: 'Seleziona le lingue in cui devono essere compilati gli elementi del menu',
    addCategory: 'Aggiungi categoria',
    editCategory: 'Modifica categoria',
    saved: 'Salvato',
    translateDiscount: 'Traduci nome sconto',
    discountDisplayName: 'Nome visualizzato',
    saveCategories: 'Salva categorie',
    categorySettingsSubtitle: 'Seleziona le categorie da mostrare nel menu',
    drinks: 'Bevande',
    main: 'Piatti principali',
    salads: 'Insalate',
    soups: 'Zuppe',
    desserts: 'Dolci',
    bakery: 'Panetteria',
    pastry: 'Pasticceria',
    appetizers: 'Antipasti',
    dips: 'Salse da intingolo',
    sauces: 'Salse',
    bestsellers: 'I più venduti',
    combo: 'Combo',
    offers: 'Offerte',
    additives: 'Aggiunte',
    seafood: 'Frutti di mare',
    pizza: 'Pizza',
    fastfood: 'Fast food',
    burgers: 'Hamburger',
    hotdogs: 'Hot dog',
    vegetarian: 'Vegetariano',
    sushi: 'Sushi',
    special: 'Piatti speciali',
    targetingLabel: 'Targeting',
    targetingHint: 'lascia vuoto = tutti gli articoli',
    specificItems: 'Articoli specifici',
    chooseFile: 'Scegli file',
    noFileChosen: 'Nessun file scelto',
    orPasteImageUrl: "o incolla un URL dell'immagine",
    imageUrlPlaceholder: 'https://esempio.com/immagine.jpg',
    ingredientsPlaceholder: 'Elenca gli ingredienti principali…',
    titlePlaceholder: 'es. Salmone alla griglia',
    languages: { en: 'Inglese', ru: 'Russo', uz: 'Uzbeco', pl: 'Polacco', es: 'Spagnolo', tr: 'Turco', ar: 'Arabo', zh: 'Cinese', ja: 'Giapponese', ko: 'Coreano', pt: 'Portoghese', fr: 'Francese', it: 'Italiano' },
    required: 'obbligatorio',
    optional: 'facoltativo',
    currency: 'Valuta',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('lang') || 'en'
  );
  const [allowedLanguages, setAllowedLanguages] = useState(['en']);

  const setLang = (l) => {
    localStorage.setItem('lang', l);
    setLangState(l);
  };

  // RTL support for Arabic
  useEffect(() => {
    document.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const refreshSettings = () =>
    fetchSettings()
      .then((res) => {
        const langs = res.data.languages || ['en'];
        const unique = [...new Set(langs)];
        setAllowedLanguages(unique);
        setLangState((prev) =>
          unique.includes(prev) ? prev : unique.includes('en') ? 'en' : unique[0]
        );
      })
      .catch(() => {});

  useEffect(() => {
    refreshSettings();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <LanguageContext.Provider
      value={{
        lang,
        setLang,
        t: translations[lang] || translations['en'],
        allowedLanguages,
        setAllowedLanguages,
        refreshSettings,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
