import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    menu: 'Menu',
    dashboard: 'Dashboard',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    cancel: 'Cancel',
    update: 'Update Item',
    saving: 'Saving…',
    categories: {
      All: 'All',
      Drinks: 'Drinks',
      'Main Dishes': 'Main Dishes',
      Salads: 'Salads',
      Soups: 'Soups',
      Desserts: 'Desserts',
    },
    hero: {
      tagline: 'Fine Dining Experience',
      subtitle: 'Authentic flavors from Central Asia, crafted with the finest ingredients',
      scroll: 'Scroll',
    },
    specialOffers: 'Special Offers',
    noItems: 'No items in this category yet.',
    loading: 'Loading menu…',
    restaurantDashboard: 'Restaurant Dashboard',
    itemsInMenu: 'items in the menu',
    globalDiscounts: 'Global Discounts',
    addDiscount: 'Add Discount',
    noDiscounts: 'No discounts yet.',
    discountTitle: 'Title',
    discountPct: 'Discount %',
    appliesTo: 'Applies To',
    everyone: 'Everyone',
    specificGroup: 'Specific Group',
    startTime: 'Start Time',
    endTime: 'End Time',
    active: 'Active',
    edit: 'Edit',
    delete: 'Delete',
    image: 'Image',
    title: 'Title',
    price: 'Price (USD)',
    category: 'Category',
    ingredients: 'Ingredients',
    discountSection: 'Item Discount',
    discountActive: 'Discount Active',
    discountPercent: 'Discount %',
    discountStart: 'Discount Start',
    discountEnd: 'Discount End',
    confirmDelete: 'Confirm Delete',
    doYouWantToDelete: 'Do you really want to delete this',
    yesDelete: 'Yes, Delete',
    noItemsYet: 'No items yet.',
    addFirstItem: 'Add your first item',
    off: 'OFF',
    sale: 'SALE',
    activeNow: 'Active Now',
    until: 'until',
  },
  ru: {
    menu: 'Меню',
    dashboard: 'Панель',
    addItem: 'Добавить',
    editItem: 'Редактировать',
    cancel: 'Отмена',
    update: 'Обновить',
    saving: 'Сохранение…',
    categories: {
      All: 'Все',
      Drinks: 'Напитки',
      'Main Dishes': 'Основные блюда',
      Salads: 'Салаты',
      Soups: 'Супы',
      Desserts: 'Десерты',
    },
    hero: {
      tagline: 'Изысканный ужин',
      subtitle: 'Аутентичные вкусы Центральной Азии, приготовленные из лучших ингредиентов',
      scroll: 'Листать',
    },
    specialOffers: 'Специальные предложения',
    noItems: 'Нет позиций в этой категории.',
    loading: 'Загрузка меню…',
    restaurantDashboard: 'Панель управления',
    itemsInMenu: 'позиций в меню',
    globalDiscounts: 'Глобальные скидки',
    addDiscount: 'Добавить скидку',
    noDiscounts: 'Скидок пока нет.',
    discountTitle: 'Название',
    discountPct: 'Скидка %',
    appliesTo: 'Применяется к',
    everyone: 'Всем',
    specificGroup: 'Конкретная группа',
    startTime: 'Начало',
    endTime: 'Конец',
    active: 'Активно',
    edit: 'Редактировать',
    delete: 'Удалить',
    image: 'Изображение',
    title: 'Название',
    price: 'Цена (USD)',
    category: 'Категория',
    ingredients: 'Ингредиенты',
    discountSection: 'Скидка на блюдо',
    discountActive: 'Скидка активна',
    discountPercent: 'Скидка %',
    discountStart: 'Начало скидки',
    discountEnd: 'Конец скидки',
    confirmDelete: 'Подтвердить удаление',
    doYouWantToDelete: 'Вы действительно хотите удалить',
    yesDelete: 'Да, удалить',
    noItemsYet: 'Нет позиций.',
    addFirstItem: 'Добавить первую позицию',
    off: 'СКИДКА',
    sale: 'АКЦИЯ',
    activeNow: 'Активно',
    until: 'до',
  },
  uz: {
    menu: 'Menyu',
    dashboard: 'Boshqaruv',
    addItem: "Qo'shish",
    editItem: 'Tahrirlash',
    cancel: 'Bekor qilish',
    update: 'Yangilash',
    saving: 'Saqlanmoqda…',
    categories: {
      All: 'Barchasi',
      Drinks: 'Ichimliklar',
      'Main Dishes': 'Asosiy taomlar',
      Salads: 'Salatlar',
      Soups: "Sho'rvalar",
      Desserts: 'Desertlar',
    },
    hero: {
      tagline: 'Hashamatli oshxona',
      subtitle: "O'rta Osiyo autentik ta'mlari, eng yaxshi ingredientlardan tayyorlangan",
      scroll: 'Aylantirish',
    },
    specialOffers: 'Maxsus takliflar',
    noItems: 'Bu kategoriyada mahsulot yo\'q.',
    loading: 'Menyu yuklanmoqda…',
    restaurantDashboard: 'Boshqaruv paneli',
    itemsInMenu: 'ta menyu elementi',
    globalDiscounts: 'Global chegirmalar',
    addDiscount: "Chegirma qo'shish",
    noDiscounts: 'Hali chegirma yo\'q.',
    discountTitle: 'Sarlavha',
    discountPct: 'Chegirma %',
    appliesTo: 'Kimga tegishli',
    everyone: 'Hammaga',
    specificGroup: 'Maxsus guruh',
    startTime: 'Boshlanish',
    endTime: 'Tugash',
    active: 'Faol',
    edit: 'Tahrirlash',
    delete: "O'chirish",
    image: 'Rasm',
    title: 'Sarlavha',
    price: 'Narx (USD)',
    category: 'Kategoriya',
    ingredients: 'Ingredientlar',
    discountSection: 'Mahsulot chegirmasi',
    discountActive: 'Chegirma faol',
    discountPercent: 'Chegirma %',
    discountStart: 'Chegirma boshlanishi',
    discountEnd: 'Chegirma tugashi',
    confirmDelete: "O'chirishni tasdiqlang",
    doYouWantToDelete: "Haqiqatan ham o'chirmoqchimisiz",
    yesDelete: "Ha, o'chirish",
    noItemsYet: 'Hali mahsulot yo\'q.',
    addFirstItem: 'Birinchi mahsulotni qo\'shish',
    off: 'CHEGIRMA',
    sale: 'AKSIYA',
    activeNow: 'Faol',
    until: 'gacha',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('lang') || 'en'
  );

  const setLang = (l) => {
    localStorage.setItem('lang', l);
    setLangState(l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
