import { createContext, useContext, useState, useEffect } from 'react';
import { fetchSettings } from '../api/settings';

const translations = {
  en: {
    menu: 'Menu',
    dashboard: 'Dashboard',
    addItem: 'Add Item',
    editItem: 'Edit Item',
    cancel: 'Cancel',
    update: 'Update Item',
    saving: 'Saving…',
    all: 'All',
    heroTitle: 'Our Menu',
    saveLanguages: 'Save Languages',
    menuLanguages: 'Menu Languages',
    menuCategories: 'Menu Categories',
    currentPromotions: 'Current Promotions',
    forEveryone: 'For Everyone',
    for: 'For',
    expired: 'Expired',
    footerTagline: 'Authentic Flavors · Crafted With Love',
    hero: {
      tagline: 'Fine Dining Experience',
      subtitle: 'Authentic flavors from Central Asia, crafted with the finest ingredients',
      scroll: 'Scroll',
    },
    specialOffers: 'Special Offers',
    noItems: 'No items in this category yet.',
    loading: 'Loading menu…',
    restaurantDashboard: 'Restaurant Dashboard',
    itemsInMenu: 'items in the menu',
    globalDiscounts: 'Global Discounts',
    addDiscount: 'Add Discount',
    noDiscounts: 'No discounts yet.',
    discountTitle: 'Title',
    discountPct: 'Discount %',
    appliesTo: 'Applies To',
    everyone: 'Everyone',
    specificGroup: 'Specific Group',
    startTime: 'Start Time',
    endTime: 'End Time',
    active: 'Active',
    edit: 'Edit',
    delete: 'Delete',
    image: 'Image',
    title: 'Title',
    price: 'Price (USD)',
    category: 'Category',
    ingredients: 'Ingredients',
    discountSection: 'Item Discount',
    discountActive: 'Discount Active',
    discountPercent: 'Discount %',
    discountStart: 'Discount Start',
    discountEnd: 'Discount End',
    confirmDelete: 'Confirm Delete',
    doYouWantToDelete: 'Do you really want to delete this',
    yesDelete: 'Yes, Delete',
    noItemsYet: 'No items yet.',
    addFirstItem: 'Add your first item',
    off: 'OFF',
    sale: 'SALE',
    activeNow: 'Active Now',
    until: 'until',
  },
  ru: {
    menu: 'Меню',
    dashboard: 'Панель',
    addItem: 'Добавить',
    editItem: 'Редактировать',
    cancel: 'Отмена',
    update: 'Обновить',
    saving: 'Сохранение…',
    all: 'Все',
    heroTitle: 'Наше меню',
    saveLanguages: 'Сохранить языки',
    menuLanguages: 'Языки меню',
    menuCategories: 'Категории меню',
    currentPromotions: 'Текущие акции',
    forEveryone: 'Для всех',
    for: 'Для',
    expired: 'Истёк',
    footerTagline: 'Аутентичные вкусы · Приготовленные с любовью',
    hero: {
      tagline: 'Изысканный ужин',
      subtitle: 'Аутентичные вкусы Центральной Азии, приготовленные из лучших ингредиентов',
      scroll: 'Листать',
    },
    specialOffers: 'Специальные предложения',
    noItems: 'Нет позиций в этой категории.',
    loading: 'Загрузка меню…',
    restaurantDashboard: 'Панель управления',
    itemsInMenu: 'позиций в меню',
    globalDiscounts: 'Глобальные скидки',
    addDiscount: 'Добавить скидку',
    noDiscounts: 'Скидок пока нет.',
    discountTitle: 'Название',
    discountPct: 'Скидка %',
    appliesTo: 'Применяется к',
    everyone: 'Всем',
    specificGroup: 'Конкретная группа',
    startTime: 'Начало',
    endTime: 'Конец',
    active: 'Активно',
    edit: 'Редактировать',
    delete: 'Удалить',
    image: 'Изображение',
    title: 'Название',
    price: 'Цена (USD)',
    category: 'Категория',
    ingredients: 'Ингредиенты',
    discountSection: 'Скидка на блюдо',
    discountActive: 'Скидка активна',
    discountPercent: 'Скидка %',
    discountStart: 'Начало скидки',
    discountEnd: 'Конец скидки',
    confirmDelete: 'Подтвердить удаление',
    doYouWantToDelete: 'Вы действительно хотите удалить',
    yesDelete: 'Да, удалить',
    noItemsYet: 'Нет позиций.',
    addFirstItem: 'Добавить первую позицию',
    off: 'СКИДКА',
    sale: 'АКЦИЯ',
    activeNow: 'Активно',
    until: 'до',
  },
  uz: {
    menu: 'Menyu',
    dashboard: 'Boshqaruv',
    addItem: "Qo'shish",
    editItem: 'Tahrirlash',
    cancel: 'Bekor qilish',
    update: 'Yangilash',
    saving: 'Saqlanmoqda…',
    all: 'Barchasi',
    heroTitle: 'Bizning menyu',
    saveLanguages: 'Tillarni saqlash',
    menuLanguages: 'Menyu tillari',
    menuCategories: 'Menyu kategoriyalari',
    currentPromotions: 'Joriy aksiyalar',
    forEveryone: 'Hammaga',
    for: 'Uchun',
    expired: 'Tugadi',
    footerTagline: 'Haqiqiy ta\'mlar · Muhabbat bilan tayyorlangan',
    hero: {
      tagline: 'Hashamatli oshxona',
      subtitle: "O'rta Osiyo autentik ta'mlari, eng yaxshi ingredientlardan tayyorlangan",
      scroll: 'Aylantirish',
    },
    specialOffers: 'Maxsus takliflar',
    noItems: "Bu kategoriyada mahsulot yo'q.",
    loading: 'Menyu yuklanmoqda…',
    restaurantDashboard: 'Boshqaruv paneli',
    itemsInMenu: 'ta menyu elementi',
    globalDiscounts: 'Global chegirmalar',
    addDiscount: "Chegirma qo'shish",
    noDiscounts: "Hali chegirma yo'q.",
    discountTitle: 'Sarlavha',
    discountPct: 'Chegirma %',
    appliesTo: 'Kimga tegishli',
    everyone: 'Hammaga',
    specificGroup: 'Maxsus guruh',
    startTime: 'Boshlanish',
    endTime: 'Tugash',
    active: 'Faol',
    edit: 'Tahrirlash',
    delete: "O'chirish",
    image: 'Rasm',
    title: 'Sarlavha',
    price: 'Narx (USD)',
    category: 'Kategoriya',
    ingredients: 'Ingredientlar',
    discountSection: 'Mahsulot chegirmasi',
    discountActive: 'Chegirma faol',
    discountPercent: 'Chegirma %',
    discountStart: 'Chegirma boshlanishi',
    discountEnd: 'Chegirma tugashi',
    confirmDelete: "O'chirishni tasdiqlang",
    doYouWantToDelete: "Haqiqatan ham o'chirmoqchimisiz",
    yesDelete: "Ha, o'chirish",
    noItemsYet: "Hali mahsulot yo'q.",
    addFirstItem: "Birinchi mahsulotni qo'shish",
    off: 'CHEGIRMA',
    sale: 'AKSIYA',
    activeNow: 'Faol',
    until: 'gacha',
  },
  pl: {
    menu: 'Menu',
    dashboard: 'Panel',
    addItem: 'Dodaj',
    editItem: 'Edytuj',
    cancel: 'Anuluj',
    update: 'Zaktualizuj',
    saving: 'Zapisywanie…',
    all: 'Wszystkie',
    heroTitle: 'Nasze menu',
    saveLanguages: 'Zapisz języki',
    menuLanguages: 'Języki menu',
    menuCategories: 'Kategorie menu',
    currentPromotions: 'Bieżące promocje',
    forEveryone: 'Dla wszystkich',
    for: 'Dla',
    expired: 'Wygasło',
    footerTagline: 'Autentyczne smaki · Przygotowane z miłością',
    hero: {
      tagline: 'Wykwintna kuchnia',
      subtitle: 'Autentyczne smaki Azji Środkowej, przygotowane z najlepszych składników',
      scroll: 'Przewiń',
    },
    specialOffers: 'Oferty specjalne',
    noItems: 'Brak pozycji w tej kategorii.',
    loading: 'Ładowanie menu…',
    restaurantDashboard: 'Panel restauracji',
    itemsInMenu: 'pozycji w menu',
    globalDiscounts: 'Globalne zniżki',
    addDiscount: 'Dodaj zniżkę',
    noDiscounts: 'Brak zniżek.',
    discountTitle: 'Tytuł',
    discountPct: 'Zniżka %',
    appliesTo: 'Dotyczy',
    everyone: 'Wszyscy',
    specificGroup: 'Konkretna grupa',
    startTime: 'Początek',
    endTime: 'Koniec',
    active: 'Aktywne',
    edit: 'Edytuj',
    delete: 'Usuń',
    image: 'Obraz',
    title: 'Tytuł',
    price: 'Cena (USD)',
    category: 'Kategoria',
    ingredients: 'Składniki',
    discountSection: 'Zniżka na produkt',
    discountActive: 'Zniżka aktywna',
    discountPercent: 'Zniżka %',
    discountStart: 'Początek zniżki',
    discountEnd: 'Koniec zniżki',
    confirmDelete: 'Potwierdź usunięcie',
    doYouWantToDelete: 'Czy chcesz usunąć',
    yesDelete: 'Tak, usuń',
    noItemsYet: 'Brak pozycji.',
    addFirstItem: 'Dodaj pierwszą pozycję',
    off: 'ZNIŻKA',
    sale: 'PROMOCJA',
    activeNow: 'Aktywne',
    until: 'do',
  },
  es: {
    menu: 'Menú',
    dashboard: 'Panel',
    addItem: 'Agregar',
    editItem: 'Editar',
    cancel: 'Cancelar',
    update: 'Actualizar',
    saving: 'Guardando…',
    all: 'Todos',
    hero: {
      tagline: 'Gastronomía fina',
      subtitle: 'Sabores auténticos de Asia Central, elaborados con los mejores ingredientes',
      scroll: 'Desplazar',
    },
    specialOffers: 'Ofertas especiales',
    noItems: 'Sin elementos en esta categoría.',
    loading: 'Cargando menú…',
    restaurantDashboard: 'Panel del restaurante',
    itemsInMenu: 'elementos en el menú',
    globalDiscounts: 'Descuentos globales',
    addDiscount: 'Agregar descuento',
    noDiscounts: 'Sin descuentos.',
    discountTitle: 'Título',
    discountPct: 'Descuento %',
    appliesTo: 'Aplica a',
    everyone: 'Todos',
    specificGroup: 'Grupo específico',
    startTime: 'Inicio',
    endTime: 'Fin',
    active: 'Activo',
    edit: 'Editar',
    delete: 'Eliminar',
    image: 'Imagen',
    title: 'Título',
    price: 'Precio (USD)',
    category: 'Categoría',
    ingredients: 'Ingredientes',
    discountSection: 'Descuento del artículo',
    discountActive: 'Descuento activo',
    discountPercent: 'Descuento %',
    discountStart: 'Inicio del descuento',
    discountEnd: 'Fin del descuento',
    confirmDelete: 'Confirmar eliminación',
    doYouWantToDelete: '¿Desea eliminar',
    yesDelete: 'Sí, eliminar',
    noItemsYet: 'Sin elementos aún.',
    addFirstItem: 'Agregar primer elemento',
    off: 'DESC',
    sale: 'OFERTA',
    activeNow: 'Activo',
    until: 'hasta',
  },
  tr: {
    menu: 'Menü',
    dashboard: 'Panel',
    addItem: 'Ekle',
    editItem: 'Düzenle',
    cancel: 'İptal',
    update: 'Güncelle',
    saving: 'Kaydediliyor…',
    all: 'Tümü',
    hero: {
      tagline: 'İnce Yemek Deneyimi',
      subtitle: "Orta Asya'nın özgün lezzetleri, en iyi malzemelerle hazırlanmış",
      scroll: 'Kaydır',
    },
    specialOffers: 'Özel Teklifler',
    noItems: 'Bu kategoride ürün yok.',
    loading: 'Menü yükleniyor…',
    restaurantDashboard: 'Restoran Paneli',
    itemsInMenu: 'menüdeki ürün',
    globalDiscounts: 'Global İndirimler',
    addDiscount: 'İndirim Ekle',
    noDiscounts: 'Henüz indirim yok.',
    discountTitle: 'Başlık',
    discountPct: 'İndirim %',
    appliesTo: 'Uygulanır',
    everyone: 'Herkes',
    specificGroup: 'Belirli Grup',
    startTime: 'Başlangıç',
    endTime: 'Bitiş',
    active: 'Aktif',
    edit: 'Düzenle',
    delete: 'Sil',
    image: 'Resim',
    title: 'Başlık',
    price: 'Fiyat (USD)',
    category: 'Kategori',
    ingredients: 'Malzemeler',
    discountSection: 'Ürün İndirimi',
    discountActive: 'İndirim Aktif',
    discountPercent: 'İndirim %',
    discountStart: 'İndirim Başlangıcı',
    discountEnd: 'İndirim Bitişi',
    confirmDelete: 'Silmeyi Onayla',
    doYouWantToDelete: 'Silmek istiyor musunuz',
    yesDelete: 'Evet, Sil',
    noItemsYet: 'Henüz ürün yok.',
    addFirstItem: 'İlk ürünü ekle',
    off: 'İNDİRİM',
    sale: 'KAMPANYA',
    activeNow: 'Aktif',
    until: 'kadar',
  },
  ar: {
    menu: 'قائمة الطعام',
    dashboard: 'لوحة التحكم',
    addItem: 'إضافة',
    editItem: 'تعديل',
    cancel: 'إلغاء',
    update: 'تحديث',
    saving: 'جارٍ الحفظ…',
    all: 'الكل',
    hero: {
      tagline: 'تجربة طعام راقية',
      subtitle: 'نكهات أصيلة من آسيا الوسطى، مُعدَّة بأجود المكونات',
      scroll: 'تمرير',
    },
    specialOffers: 'عروض خاصة',
    noItems: 'لا توجد عناصر في هذه الفئة.',
    loading: 'جارٍ تحميل القائمة…',
    restaurantDashboard: 'لوحة تحكم المطعم',
    itemsInMenu: 'عناصر في القائمة',
    globalDiscounts: 'الخصومات العامة',
    addDiscount: 'إضافة خصم',
    noDiscounts: 'لا توجد خصومات.',
    discountTitle: 'العنوان',
    discountPct: 'نسبة الخصم',
    appliesTo: 'ينطبق على',
    everyone: 'الجميع',
    specificGroup: 'مجموعة محددة',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    active: 'نشط',
    edit: 'تعديل',
    delete: 'حذف',
    image: 'صورة',
    title: 'العنوان',
    price: 'السعر (USD)',
    category: 'الفئة',
    ingredients: 'المكونات',
    discountSection: 'خصم العنصر',
    discountActive: 'الخصم نشط',
    discountPercent: 'نسبة الخصم',
    discountStart: 'بداية الخصم',
    discountEnd: 'نهاية الخصم',
    confirmDelete: 'تأكيد الحذف',
    doYouWantToDelete: 'هل تريد حذف',
    yesDelete: 'نعم، حذف',
    noItemsYet: 'لا توجد عناصر.',
    addFirstItem: 'أضف العنصر الأول',
    off: 'خصم',
    sale: 'تخفيض',
    activeNow: 'نشط',
    until: 'حتى',
  },
  zh: {
    menu: '菜单',
    dashboard: '控制台',
    addItem: '添加',
    editItem: '编辑',
    cancel: '取消',
    update: '更新',
    saving: '保存中…',
    all: '全部',
    hero: {
      tagline: '精致餐饮体验',
      subtitle: '来自中亚的正宗风味，以最优质的食材精心制作',
      scroll: '滚动',
    },
    specialOffers: '特别优惠',
    noItems: '此类别暂无菜品。',
    loading: '菜单加载中…',
    restaurantDashboard: '餐厅控制台',
    itemsInMenu: '个菜单项',
    globalDiscounts: '全局折扣',
    addDiscount: '添加折扣',
    noDiscounts: '暂无折扣。',
    discountTitle: '标题',
    discountPct: '折扣 %',
    appliesTo: '适用于',
    everyone: '所有人',
    specificGroup: '特定群体',
    startTime: '开始时间',
    endTime: '结束时间',
    active: '活跃',
    edit: '编辑',
    delete: '删除',
    image: '图片',
    title: '标题',
    price: '价格 (USD)',
    category: '类别',
    ingredients: '食材',
    discountSection: '菜品折扣',
    discountActive: '折扣有效',
    discountPercent: '折扣 %',
    discountStart: '折扣开始',
    discountEnd: '折扣结束',
    confirmDelete: '确认删除',
    doYouWantToDelete: '确定要删除',
    yesDelete: '是的，删除',
    noItemsYet: '暂无菜品。',
    addFirstItem: '添加第一个菜品',
    off: '折扣',
    sale: '特卖',
    activeNow: '活跃',
    until: '至',
  },
  ja: {
    menu: 'メニュー',
    dashboard: 'ダッシュボード',
    addItem: '追加',
    editItem: '編集',
    cancel: 'キャンセル',
    update: '更新',
    saving: '保存中…',
    all: 'すべて',
    hero: {
      tagline: '高級ダイニング体験',
      subtitle: '中央アジアの本場の味わい、最高の食材で仕上げた一品',
      scroll: 'スクロール',
    },
    specialOffers: '特別オファー',
    noItems: 'このカテゴリにはまだ商品がありません。',
    loading: 'メニューを読み込み中…',
    restaurantDashboard: 'レストランダッシュボード',
    itemsInMenu: '個のメニュー項目',
    globalDiscounts: 'グローバル割引',
    addDiscount: '割引を追加',
    noDiscounts: '割引はまだありません。',
    discountTitle: 'タイトル',
    discountPct: '割引 %',
    appliesTo: '適用対象',
    everyone: '全員',
    specificGroup: '特定グループ',
    startTime: '開始時間',
    endTime: '終了時間',
    active: 'アクティブ',
    edit: '編集',
    delete: '削除',
    image: '画像',
    title: 'タイトル',
    price: '価格 (USD)',
    category: 'カテゴリ',
    ingredients: '食材',
    discountSection: '商品割引',
    discountActive: '割引有効',
    discountPercent: '割引 %',
    discountStart: '割引開始',
    discountEnd: '割引終了',
    confirmDelete: '削除の確認',
    doYouWantToDelete: '削除してもよろしいですか',
    yesDelete: 'はい、削除',
    noItemsYet: 'まだ商品がありません。',
    addFirstItem: '最初の商品を追加',
    off: '割引',
    sale: 'セール',
    activeNow: 'アクティブ',
    until: 'まで',
  },
  ko: {
    menu: '메뉴',
    dashboard: '대시보드',
    addItem: '추가',
    editItem: '편집',
    cancel: '취소',
    update: '업데이트',
    saving: '저장 중…',
    all: '전체',
    hero: {
      tagline: '파인 다이닝 경험',
      subtitle: '중앙아시아의 정통 맛, 최고의 재료로 만든 요리',
      scroll: '스크롤',
    },
    specialOffers: '특별 제공',
    noItems: '이 카테고리에 항목이 없습니다.',
    loading: '메뉴 로딩 중…',
    restaurantDashboard: '레스토랑 대시보드',
    itemsInMenu: '개의 메뉴 항목',
    globalDiscounts: '글로벌 할인',
    addDiscount: '할인 추가',
    noDiscounts: '할인이 없습니다.',
    discountTitle: '제목',
    discountPct: '할인 %',
    appliesTo: '적용 대상',
    everyone: '모든 사람',
    specificGroup: '특정 그룹',
    startTime: '시작 시간',
    endTime: '종료 시간',
    active: '활성',
    edit: '편집',
    delete: '삭제',
    image: '이미지',
    title: '제목',
    price: '가격 (USD)',
    category: '카테고리',
    ingredients: '재료',
    discountSection: '상품 할인',
    discountActive: '할인 활성',
    discountPercent: '할인 %',
    discountStart: '할인 시작',
    discountEnd: '할인 종료',
    confirmDelete: '삭제 확인',
    doYouWantToDelete: '삭제하시겠습니까',
    yesDelete: '예, 삭제',
    noItemsYet: '아직 항목이 없습니다.',
    addFirstItem: '첫 번째 항목 추가',
    off: '할인',
    sale: '세일',
    activeNow: '활성',
    until: '까지',
  },
  pt: {
    menu: 'Menu',
    dashboard: 'Painel',
    addItem: 'Adicionar',
    editItem: 'Editar',
    cancel: 'Cancelar',
    update: 'Atualizar',
    saving: 'A guardar…',
    all: 'Todos',
    hero: {
      tagline: 'Experiência gastronómica',
      subtitle: 'Sabores autênticos da Ásia Central, preparados com os melhores ingredientes',
      scroll: 'Rolar',
    },
    specialOffers: 'Ofertas especiais',
    noItems: 'Sem itens nesta categoria.',
    loading: 'A carregar menu…',
    restaurantDashboard: 'Painel do restaurante',
    itemsInMenu: 'itens no menu',
    globalDiscounts: 'Descontos globais',
    addDiscount: 'Adicionar desconto',
    noDiscounts: 'Sem descontos.',
    discountTitle: 'Título',
    discountPct: 'Desconto %',
    appliesTo: 'Aplica-se a',
    everyone: 'Todos',
    specificGroup: 'Grupo específico',
    startTime: 'Início',
    endTime: 'Fim',
    active: 'Ativo',
    edit: 'Editar',
    delete: 'Eliminar',
    image: 'Imagem',
    title: 'Título',
    price: 'Preço (USD)',
    category: 'Categoria',
    ingredients: 'Ingredientes',
    discountSection: 'Desconto do item',
    discountActive: 'Desconto ativo',
    discountPercent: 'Desconto %',
    discountStart: 'Início do desconto',
    discountEnd: 'Fim do desconto',
    confirmDelete: 'Confirmar eliminação',
    doYouWantToDelete: 'Deseja eliminar',
    yesDelete: 'Sim, eliminar',
    noItemsYet: 'Sem itens ainda.',
    addFirstItem: 'Adicionar primeiro item',
    off: 'DESC',
    sale: 'PROMOÇÃO',
    activeNow: 'Ativo',
    until: 'até',
  },
  fr: {
    menu: 'Menu',
    dashboard: 'Tableau de bord',
    addItem: 'Ajouter',
    editItem: 'Modifier',
    cancel: 'Annuler',
    update: 'Mettre à jour',
    saving: 'Enregistrement…',
    all: 'Tous',
    hero: {
      tagline: 'Expérience gastronomique',
      subtitle: "Saveurs authentiques d'Asie centrale, élaborées avec les meilleurs ingrédients",
      scroll: 'Défiler',
    },
    specialOffers: 'Offres spéciales',
    noItems: 'Aucun article dans cette catégorie.',
    loading: 'Chargement du menu…',
    restaurantDashboard: 'Tableau de bord',
    itemsInMenu: 'articles au menu',
    globalDiscounts: 'Réductions globales',
    addDiscount: 'Ajouter une réduction',
    noDiscounts: 'Aucune réduction.',
    discountTitle: 'Titre',
    discountPct: 'Réduction %',
    appliesTo: "S'applique à",
    everyone: 'Tout le monde',
    specificGroup: 'Groupe spécifique',
    startTime: 'Début',
    endTime: 'Fin',
    active: 'Actif',
    edit: 'Modifier',
    delete: 'Supprimer',
    image: 'Image',
    title: 'Titre',
    price: 'Prix (USD)',
    category: 'Catégorie',
    ingredients: 'Ingrédients',
    discountSection: "Réduction de l'article",
    discountActive: 'Réduction active',
    discountPercent: 'Réduction %',
    discountStart: 'Début de la réduction',
    discountEnd: 'Fin de la réduction',
    confirmDelete: 'Confirmer la suppression',
    doYouWantToDelete: 'Voulez-vous supprimer',
    yesDelete: 'Oui, supprimer',
    noItemsYet: 'Aucun article.',
    addFirstItem: 'Ajouter le premier article',
    off: 'SOLDE',
    sale: 'PROMO',
    activeNow: 'Actif',
    until: "jusqu'à",
  },
  it: {
    menu: 'Menu',
    dashboard: 'Dashboard',
    addItem: 'Aggiungi',
    editItem: 'Modifica',
    cancel: 'Annulla',
    update: 'Aggiorna',
    saving: 'Salvataggio…',
    all: 'Tutti',
    hero: {
      tagline: 'Esperienza gastronomica',
      subtitle: "Sapori autentici dall'Asia Centrale, preparati con i migliori ingredienti",
      scroll: 'Scorri',
    },
    specialOffers: 'Offerte speciali',
    noItems: 'Nessun articolo in questa categoria.',
    loading: 'Caricamento menu…',
    restaurantDashboard: 'Dashboard ristorante',
    itemsInMenu: 'articoli nel menu',
    globalDiscounts: 'Sconti globali',
    addDiscount: 'Aggiungi sconto',
    noDiscounts: 'Nessuno sconto.',
    discountTitle: 'Titolo',
    discountPct: 'Sconto %',
    appliesTo: 'Si applica a',
    everyone: 'Tutti',
    specificGroup: 'Gruppo specifico',
    startTime: 'Inizio',
    endTime: 'Fine',
    active: 'Attivo',
    edit: 'Modifica',
    delete: 'Elimina',
    image: 'Immagine',
    title: 'Titolo',
    price: 'Prezzo (USD)',
    category: 'Categoria',
    ingredients: 'Ingredienti',
    discountSection: 'Sconto articolo',
    discountActive: 'Sconto attivo',
    discountPercent: 'Sconto %',
    discountStart: 'Inizio sconto',
    discountEnd: 'Fine sconto',
    confirmDelete: 'Conferma eliminazione',
    doYouWantToDelete: 'Vuoi eliminare',
    yesDelete: 'Sì, elimina',
    noItemsYet: 'Nessun articolo.',
    addFirstItem: 'Aggiungi il primo articolo',
    off: 'SCONTO',
    sale: 'SALDO',
    activeNow: 'Attivo',
    until: 'fino a',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem('lang') || 'en'
  );
  const [allowedLanguages, setAllowedLanguages] = useState(['en']);

  const setLang = (l) => {
    localStorage.setItem('lang', l);
    setLangState(l);
  };

  // RTL support for Arabic
  useEffect(() => {
    document.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const refreshSettings = () =>
    fetchSettings()
      .then((res) => {
        const langs = res.data.languages || ['en'];
        const unique = [...new Set(langs)];
        setAllowedLanguages(unique);
        setLangState((prev) =>
          unique.includes(prev) ? prev : unique.includes('en') ? 'en' : unique[0]
        );
      })
      .catch(() => {});

  useEffect(() => {
    refreshSettings();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <LanguageContext.Provider
      value={{
        lang,
        setLang,
        t: translations[lang] || translations['en'],
        allowedLanguages,
        setAllowedLanguages,
        refreshSettings,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
