export const DEFAULT_CATEGORIES = [
  "drinks",
  "main",
  "salads",
  "soups",
  "desserts",
  "bakery",
  "pastry",
  "appetizers",
  "dips",
  "sauces",
  "bestsellers",
  "combo",
  "offers",
  "additives",
  "seafood",
  "pizza",
  "fastfood",
  "burgers",
  "hotdogs",
  "vegetarian",
  "sushi",
  "special",
];

export const CATEGORY_ICONS = {
  drinks:      "🥤",
  main:        "🍽️",
  salads:      "🥗",
  soups:       "🍲",
  desserts:    "🍰",
  bakery:      "🍞",
  pastry:      "🥐",
  appetizers:  "🥨",
  dips:        "🫕",
  sauces:      "🥫",
  bestsellers: "⭐",
  combo:       "🎁",
  offers:      "🏷️",
  additives:   "➕",
  seafood:     "🦞",
  pizza:       "🍕",
  fastfood:    "🍟",
  burgers:     "🍔",
  hotdogs:     "🌭",
  vegetarian:  "🥦",
  sushi:       "🍣",
  special:     "✨",
};
